[project]
name = "my-first-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gradio>=5.23.3",
    "litellm>=1.65.4.post1",
    "smolagents>=1.13.0",
]
